In [1]:
import numpy as np

In [3]:
np.random.seed(0)
x1 = np.random.randint(10, size = 6)
x2 = np.random.randint(10, size = (3,4))
x3 = np.random.randint(10, size = (3,4,5))

In [13]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int64
itemsize: 8 bytes
nbytes: 480 bytes


In [14]:
x1

array([5, 0, 3, 3, 7, 9])

In [16]:
x1[-1]

9

In [17]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [18]:
x2[2,0]

1

In [19]:
x2[0,0] = 12

In [20]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [21]:
x1[0] = 3.14159
x1

array([3, 0, 3, 3, 7, 9])

In [22]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
x[:5]

array([0, 1, 2, 3, 4])

In [24]:
x[5:]

array([5, 6, 7, 8, 9])

In [25]:
x[4:7]

array([4, 5, 6])

In [32]:
x[::2]

array([0, 2, 4, 6, 8])

In [33]:
x[1::2]

array([1, 3, 5, 7, 9])

In [34]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [36]:
x[7::-2]

array([7, 5, 3, 1])

In [37]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [41]:
x2[(True,True,False),]

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8]])

In [42]:
x2[:2,]

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8]])

In [43]:
x2[:2,:3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [45]:
x2[:3,::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [48]:
x2[:,0] = (1,2,3)
x2

array([[1, 5, 2, 4],
       [2, 6, 8, 8],
       [3, 6, 7, 7]])

In [51]:
x2[:,0] = [-1,-2,-3]
x2

array([[-1,  5,  2,  4],
       [-2,  6,  8,  8],
       [-3,  6,  7,  7]])

In [52]:
x2.dtype

dtype('int64')

In [56]:
x2
x2_sub = x2[:2,:2]
x2_sub

array([[-1,  5],
       [-2,  6]])

In [57]:
x2_sub[0,0] = 99
print(x2_sub)
print(x2)

[[99  5]
 [-2  6]]
[[99  5  2  4]
 [-2  6  8  8]
 [-3  6  7  7]]


In [58]:
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)
x2_sub_copy[0,0] = 42
print(x2_sub_copy)
print(x2)

[[99  5]
 [-2  6]]
[[42  5]
 [-2  6]]
[[99  5  2  4]
 [-2  6  8  8]
 [-3  6  7  7]]


In [60]:
grid  = np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [63]:
x.reshape((1,3))

array([[1, 2, 3]])

In [64]:
x[np.newaxis,:]

array([[1, 2, 3]])

In [65]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [66]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [68]:
x = np.array([1,2,3])
y = np.array([3,2,1])
z = [99,99,99]
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [73]:
grid = np.array([1,2,3,4,5,6]).reshape((2,3))
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [74]:
np.concatenate((grid,grid), axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [85]:
x = np.array((1,2,3))
grid = np.array([9,8,7,6,5,4]).reshape((2,3))
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [86]:
y = np.array([99,99]).reshape((2,1))
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [88]:
x = [1,2,3,99,99,3,2,1]
x1, x2, x3 = np.split(x,[3,5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [90]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [92]:
upper, lower = np.vsplit(grid,2)
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [93]:
left, right = np.hsplit(grid, 2)
print(left,right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [94]:
left[0,0] = -100
print(left)
print(grid)

[[-100    1]
 [   4    5]
 [   8    9]
 [  12   13]]
[[-100    1    2    3]
 [   4    5    6    7]
 [   8    9   10   11]
 [  12   13   14   15]]


In [96]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([ 0.2       ,  0.25      ,  0.2       ,  0.2       ,  0.11111111])

In [97]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

3.49 s ± 27.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [98]:
%timeit (1 / big_array)

8.68 ms ± 5.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [99]:
np.arange(5) / np.arange(1,6)

array([ 0.        ,  0.5       ,  0.66666667,  0.75      ,  0.8       ])

In [100]:
x = np.arange(9).reshape((3,3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [102]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division
print("-x = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)


x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [ 0.   0.5  1.   1.5]
x // 2 = [0 0 1 1]
-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


In [103]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [104]:
x= np.array((-2,-1,0,1,2))
%timeit abs(x)

676 ns ± 27.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [105]:
%timeit np.abs(x)

660 ns ± 92.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
